---
new_page_extension: md
auto_deploy: true
admin_path: ".vuepress/public/admin"
webhook_url: 
sections:
- type: directory
  path: stuff1
  label: Another
  create: all
  match: "**/*"
- type: document
  path: ".vuepress/config.js"
  label: Config
- type: heading
  label: Stuff
- type: directory
  path: ''
  label: Pages
  create: all
  match: "**/*.md"
  templates:
  - page
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: node:10
  mount_path: "/srv"
  instant_preview_command: vuepress dev -p 8080 -h 0.0.0.0
